### ISSUE TITLE
WIN10, 설치시 오류 해결법입니다.

### ISSUE THREAD

**Issue by ingus26** [limerainne/PaperProKitchen#2]
문의 작성 후 해결이 안되서 Close했었습니다.
해결하고 다시 올려요..

※ WIN 10의 문제라기 보다 github에서 zip파일로 다운받아서 압축을 해제할 때 
파일 손실이 발생해서 그런것 같다는 생각이듭니다.
압축 해제해서 img파일의 경우 1KB로 다운받아지는 데
페이지에 들어가서 다운받을 경우 용량 차이가 나네요

루팅 성공적으로 했습니다 감사합니다 :D 

환경
- 윈도우10 엔터프라이즈 64bit

문제
- GoogleUSBDriver 폴더의 android_winusb.inf 파일 설치시 오류 메세지
  '지정한 카탈로그 파일에 이 파일에 대한 해시가 없습니다. 파일이 손상되거나 훼손된 것같습니다'

해결
- https://developer.android.com/studio/run/win-usb?hl=ko 에서 Google USB 드라이버 설치
 
※ 그리고 드라이버 설치 후 장치 관리자에서 '보기(V)' > 숨겨진 장치 표시(W)를 해야 
    연결된 항목이 보였습니다.

**Comment by limerainne** [comment]
댓글이 많이 늦었지만, 문제 사항 알려주셔서 감사합니다. 일단 말씀하신 원인이 맞다고 보입니다.
저장소의 `소스 ZIP 파일` 말고, 제가 릴리스 페이지에 올린 압축 파일을 받으시길 바랍니다. 이미 그렇게 하신 것 같고요.

-----

릴리스 페이지에 직접 올린 압축 파일은 제 윈도 PC에서 직접 압축한거라, 원본 드라이버 파일이 정상적으로 들어갔고요.

Git 저장소에 있는 드라이버 파일 중 `android_winusb.inf` 파일은,
해당 텍스트 파일이 Git 저장소에 들어갈 때 개행 문자가 "CR+LF"에서 "LF"로 변환된 바람에,
(오류 메시지 그대로) 해시 값이 바뀌어서 설치에 실패하는 것으로 보입니다.

릴리스에 직접 올린 압축 파일 말고, 
Git 저장소의 파일은 "버전 관리용 + 패키지에 이상한 것 안 넣었음 증빙용 + GitHub 사용법 연습용"일 뿐입니다.

저장소에서 소스 ZIP 파일을 다운받았을 때 이미지 파일이 모두 1KB인 것도 GitHub (LFS) 사용법 연습해서 그렇습니다..

-----

`숨겨진 장치 표시`해야 기기가 보이는 상황은 새롭네요.. 왜 그런지 잘 모르겠습니다.
